# Generated by Django 4.1.1 on 2022-10-26 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostTitle', models.CharField(max_length=50)),
                ('PostDate', models.DateField()),
                ('PostStatus', models.CharField(choices=[('P', 'Published'), ('H', 'Hidden'), ('D', 'Deleted')], max_length=1)),
                ('OwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostText', models.CharField(max_length=250)),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=100)),
                ('CommentDate', models.DateField()),
                ('CommentStatus', models.CharField(choices=[('A', 'Published'), ('P', 'Pending'), ('D', 'Decliend')], max_length=1)),
                ('CommentPostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('CommenterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
