# Generated by Django 4.1.1 on 2022-11-03 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_tag_rename_ownerid_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Featured_Image',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 3, 20, 33, 4, 235251, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 3, 20, 33, 4, 236422, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 3, 20, 33, 4, 235967, tzinfo=datetime.timezone.utc)),
        ),
    ]
