# Generated by Django 4.1.1 on 2022-11-03 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_featured_image_alter_category_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 3, 20, 33, 58, 141981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 3, 20, 33, 58, 143278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Featured_Image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 3, 20, 33, 58, 142835, tzinfo=datetime.timezone.utc)),
        ),
    ]
