# Generated by Django 4.1.1 on 2022-11-20 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_category_date_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 3, 44, 4, 636753, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 3, 44, 4, 638406, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 3, 44, 4, 637728, tzinfo=datetime.timezone.utc)),
        ),
    ]
