# Generated by Django 4.1.1 on 2022-11-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_slug_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='Parent',
            field=models.IntegerField(default=0),
        ),
    ]
