# Generated by Django 4.1.1 on 2022-11-20 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 3, 52, 18, 958192, tzinfo=datetime.timezone.utc)),
        ),
    ]
